server:
  port: 8080

spring:
  rabbitmq:
#    stomp.port: 15670
    host: 127.0.0.1
    port: 5672
    username: eddie
    password: eddie
    publisher-returns: true
    template:
      mandatory: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        retry:
          max-attempts: 3
          enabled: true
    virtual-host: /
    publisher-confirms: true
  resources:
    static-locations: classpath:/template/,classpath:/static/,classpath:/META-INF/resources/
  mvc:
    static-path-pattern: classpath:/static/**,classpath:/template/**

mq:
  prefix: eddie
  exchangeName: ${mq.prefix}_customExchange
  user:
    queue: ${mq.prefix}_user_queue
    routingKey: ${mq.prefix}_userKey

