server:
  port: 8080

spring:
  rabbitmq:
    stomp.port: 15670
    host: 127.0.0.1
    port: 5672
    username: eddie
    password: eddie
    publisher-returns: true
    template:
      mandatory: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: auto
  web:
    resources:
      static-locations: file:D:/ed/,classpath:/,classpath:/resource/

mq:
  prefix: eddie
  exchangeName: ${mq.prefix}_customExchange
  user:
    queue: ${mq.prefix}_user_queue
    routingKey: ${mq.prefix}_userKey

